import { generateMetadata as genMeta, pageMetadata } from '@/lib/seo-metadata';

export const metadata = genMeta(pageMetadata.terms);

export default function Terms() {
  return (
    <div className="container py-16 max-w-3xl">
        <h1 className="font-heading text-4xl font-bold mb-8">Terms of Service</h1>
        <div className="prose dark:prose-invert">
          <p className="text-lg text-muted-foreground mb-6">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
          
          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using SecureGen (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">2. Description of Service</h2>
            <p>
              SecureGen is a free, web-based utility for generating cryptographically secure passwords. All generation processes occur client-side within the user's browser.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">3. Use of Generated Passwords</h2>
            <p>
              You are solely responsible for the use, storage, and management of any passwords generated by the Service. While SecureGen uses standard cryptographic practices (Web Crypto API) for generation, no password is 100% uncrackable. The degree of security depends significantly on password length, complexity, and how you store and use the password.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">4. Disclaimers & Limitation of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
            </p>
            <p className="mt-4">
              SecureGen and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of access to accounts, or financial loss arising from:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>The use of passwords generated by the Service.</li>
              <li>Unauthorized access to your accounts.</li>
              <li>Data breaches on third-party websites where generated passwords are used.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">5. Modifications to Service</h2>
            <p>
              We reserve the right to modify or discontinue the Service (or any part thereof) at any time without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">6. Open Source License</h2>
            <p>
              The source code for SecureGen is open source and available under the MIT License. You can find the source code and license details on our <a href="https://github.com/kevinmathukiya/SecureGen" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">GitHub repository</a>.
            </p>
          </section>
        </div>
    </div>
  );
}

