import { generateMetadata as genMeta, pageMetadata } from '@/lib/seo-metadata';
import Link from 'next/link';

export const metadata = genMeta(pageMetadata.terms);

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      {/* ── Hero Section ── */}
      <section className="relative pt-16 pb-12 overflow-hidden border-b border-border">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 left-1/2 w-[600px] h-[300px] bg-primary/5 rounded-full blur-[100px] -translate-x-1/2 -translate-y-1/2" />
        </div>

        <div className="container relative z-10 mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-4">Terms of Service</h1>
            <p className="text-muted-foreground text-lg">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </div>
      </section>

      {/* ── Content Section ── */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto">
            <div className="prose dark:prose-invert prose-slate max-w-none">
              <section className="mb-12">
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm">1</span>
                  Acceptance of Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  By accessing and using SecureGen (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm">2</span>
                  Description of Service
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  SecureGen is a free, web-based utility for generating cryptographically secure passwords. All generation processes occur client-side within the user's browser using the Web Crypto API.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm">3</span>
                  Use of Generated Passwords
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  You are solely responsible for the use, storage, and management of any passwords generated by the Service. While SecureGen uses standard cryptographic practices for generation, no password is 100% uncrackable. The degree of security depends significantly on password length, complexity, and how you store and use the password.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm">4</span>
                  Disclaimers & Limitation of Liability
                </h2>
                <div className="p-6 rounded-2xl bg-muted/30 border border-border">
                  <p className="font-bold mb-4 text-foreground">
                    THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
                  </p>
                  <p className="text-muted-foreground mb-4">
                    SecureGen and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from:
                  </p>
                  <ul className="space-y-2 text-muted-foreground">
                    <li className="flex items-start gap-2">
                      <svg className="w-5 h-5 text-primary shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor font-bold">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                      The use of passwords generated by the Service.
                    </li>
                    <li className="flex items-start gap-2">
                      <svg className="w-5 h-5 text-primary shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor font-bold">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                      Unauthorized access to your accounts.
                    </li>
                    <li className="flex items-start gap-2">
                      <svg className="w-5 h-5 text-primary shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor font-bold">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                      Data breaches on third-party websites.
                    </li>
                  </ul>
                </div>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm">5</span>
                  Modifications to Service
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to modify or discontinue the Service at any time without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                  <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm">6</span>
                  Open Source License
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  The source code for SecureGen is open source and available under the MIT License. You can find the source code and license details on our {' '}
                  <a
                    rel="noopener noreferrer"
                    className="text-primary font-bold hover:underline"
                  >
                    GitHub repository
                  </a>.
                </p>
              </section>
            </div>

            <div className="mt-20 p-8 rounded-3xl border border-primary/20 bg-primary/5 flex flex-col md:flex-row items-center justify-between gap-6">
              <div>
                <h3 className="text-xl font-bold mb-2">Have questions about our terms?</h3>
                <p className="text-muted-foreground">Feel free to open an issue on our repository.</p>
              </div>
              <a
                rel="noopener noreferrer"
                className="px-6 py-3 rounded-xl bg-primary text-primary-foreground font-bold hover:bg-primary/90 transition-all shadow-lg shadow-primary/20"
              >
                Contact Support
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
