import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';

export const metadata = {
  title: 'Terms of Service | SecureGen',
  description: 'Review our Terms of Service regarding the use of the SecureGen password generator tool.',
  keywords: 'terms of service, usage terms, disclaimer',
  openGraph: {
    title: 'Terms of Service | SecureGen',
    description: 'Review our Terms of Service regarding the use of the SecureGen password generator tool.',
    url: 'https://securegen.app/terms',
  },
};

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      <main className="flex-1 container py-16 max-w-3xl">
        <h1 className="font-heading text-4xl font-bold mb-8">Terms of Service</h1>
        <div className="prose dark:prose-invert">
          <p className="text-lg text-muted-foreground mb-6">
            By using SecureGen, you agree to these terms.
          </p>
          
          <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">Usage</h2>
          <p>
            SecureGen is a free tool provided "as is". While we strive for the highest security standards, we cannot be held liable for any damages arising from the use of generated passwords.
          </p>

          <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">Disclaimer</h2>
          <p>
            We do not guarantee that passwords generated by this tool are 100% uncrackable. Security depends on many factors, including how you store and use your passwords.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}

