import { generateMetadata as genMeta, pageMetadata } from '@/lib/seo-metadata';
import { generateBreadcrumbSchema } from '@/lib/schema-generators';

export const metadata = genMeta(pageMetadata.privacy);

export default function Privacy() {
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: "/" },
    { name: "Privacy Policy", url: "/privacy" }
  ]);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
    <div className="container py-16 max-w-3xl">
        <h1 className="font-heading text-4xl font-bold mb-8">Privacy Policy</h1>
        <div className="prose dark:prose-invert">
          <p className="text-lg text-muted-foreground mb-6">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
          
          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">1. Zero-Data Commitment</h2>
            <p>
              At SecureGen, we prioritize your privacy above all else. Our core service—the password generator—is designed to be <strong>100% client-side</strong>. This means that every password you generate is created locally on your device using your browser's own cryptographic functions (Web Crypto API).
            </p>
            <p className="mt-4 text-primary font-medium">
              We never see, store, or transmit your generated passwords.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">2. Information We Collect</h2>
            <h3 className="text-xl font-medium mt-6 mb-2">Usage Analytics</h3>
            <p>
              To improve our user experience and monitor site performance, we use <strong>Google Analytics 4 (GA4)</strong>. GA4 collects anonymized data such as:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>Pages visited and time spent</li>
              <li>Device type and browser information</li>
              <li>General geographic location (City/Country level)</li>
              <li>Referral sources (how you found our site)</li>
            </ul>
            <p className="mt-4 italic">
              Important: Google Analytics does NOT have access to the passwords you generate. The values generated by the tool are never sent to Google or any other third party.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">3. Local Storage & Preferences</h2>
            <p>
              We use <strong>Local Storage</strong> and <strong>Session Storage</strong> in your browser to save your tool preferences, such as:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>Dark/Light mode theme setting</li>
              <li>Your last used password length preference</li>
              <li>Character set toggles (Uppercase, Numbers, etc.)</li>
            </ul>
            <p className="mt-4">
              This data remains on your physical device and is not synchronized with any server.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">4. Cookies</h2>
            <p>
              We use minimal cookies primarily for the function of Google Analytics. You can manage your cookie preferences through your browser settings. For more details, please see our <a href="/cookies" className="text-primary hover:underline">Cookie Policy</a>.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="font-heading text-2xl font-semibold mt-8 mb-4">5. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy or our security practices, you can reach out via our <a href="https://github.com/kevinmathukiya/SecureGen/issues" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">GitHub repository</a>.
            </p>
          </section>
        </div>
    </div>
    </>
  );
}

